# Generated by Django 2.1.3 on 2018-11-12 03:09

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ambitos', '0004_auto_20181112_0230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de Caracteristica')),
                ('descripcion', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('numero', models.FloatField(verbose_name='Número de Característica')),
                ('encargado', models.CharField(blank=True, max_length=200, null=True, verbose_name='Encargado de Caracteristica')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('ambito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambitos.Ambito', verbose_name='Ámbito')),
            ],
            options={
                'verbose_name': 'Característica',
                'verbose_name_plural': 'Características',
                'ordering': ['numero'],
            },
        ),
    ]
