# Generated by Django 2.1.3 on 2018-11-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caracteristicas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracteristica',
            name='denominacion',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Denomiación'),
        ),
        migrations.AddField(
            model_name='caracteristica',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='documentos', verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='caracteristica',
            name='fecha',
            field=models.DateField(default='2018-11-13', verbose_name='Fecha de documento'),
        ),
    ]
