# Generated by Django 2.1.3 on 2018-11-26 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caracteristicas', '0002_auto_20181113_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracteristica',
            name='tipo',
            field=models.CharField(blank=True, choices=[('OBLIGATORIA', 'OBLIGATORIA'), ('NO OBLIGATORIA', 'NO OBLIGATORIA')], max_length=15, null=True, verbose_name='Tipo de caracteristica'),
        ),
    ]
