# Generated by Django 3.0.5 on 2020-04-22 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caracteristicas', '0003_caracteristica_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caracteristica',
            options={'ordering': ['ambito', 'numero'], 'verbose_name': 'Característica', 'verbose_name_plural': 'Características'},
        ),
        migrations.RemoveField(
            model_name='caracteristica',
            name='documento',
        ),
    ]
