# Generated by Django 2.1.3 on 2018-11-11 23:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de Ámbito')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Número de Ámbito')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Ámbito',
                'verbose_name_plural': 'Ámbitos',
            },
        ),
    ]
