# Generated by Django 2.1.3 on 2018-11-12 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambitos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ambit',
            new_name='Ambito',
        ),
        migrations.RenameField(
            model_name='ambito',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='ambito',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='ambito',
            old_name='number',
            new_name='numero',
        ),
    ]
