# Generated by Django 2.1.3 on 2018-11-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambitos', '0003_ambito_sigla'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ambito',
            options={'ordering': ['numero'], 'verbose_name': 'Ámbito', 'verbose_name_plural': 'Ámbitos'},
        ),
        migrations.AddField(
            model_name='ambito',
            name='encargado',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Encargado de Ámbito'),
        ),
    ]
