# Generated by Django 3.0.5 on 2020-04-22 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caracteristicas', '0004_auto_20200421_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('NOMBRAMIENTO', 'NOMBRAMIENTO'), ('PROTOCOLO', 'PROTOCOLO')], max_length=20, null=True, verbose_name='Tipo de documento')),
                ('version', models.FloatField(blank=True, null=True, verbose_name='Versión de documento')),
                ('fecha_documento', models.DateField(verbose_name='Fecha documento')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('caracteristica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caracteristicas.Caracteristica', verbose_name='Caracteristica')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['fecha_documento'],
            },
        ),
    ]
