# Generated by Django 3.0.5 on 2020-04-22 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='documentos', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(blank=True, choices=[('INDICADOR', 'INDICADOR'), ('NOMBRAMIENTO', 'NOMBRAMIENTO'), ('PROTOCOLO', 'PROTOCOLO')], max_length=20, null=True, verbose_name='Tipo de documento'),
        ),
    ]
